version: '3.4'

# services:
#   client-api:
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_URLS=http://0.0.0.0:80
#     ports:
#       - 5081:80
#     volumes:
#       - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
#       - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
#   client-api-dapr:
#     command: ["./daprd",
#      "-app-id", "client-api",
#      "-app-port", "80",
#      "-resources-path", "./components"]
  # processor:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://0.0.0.0:80
  #   ports:
  #     - 5080:80
  #   volumes:
  #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  #     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  # processor-dapr:
  #   command: ["./daprd",
  #    "-app-id", "processor",
  #    "-app-port", "80",
  #    "-resources-path", "./components"]